version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  social-rating-bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
      TOKEN: ${TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - postgres
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"